### ISSUE TITLE
please install the mysql2 adapter

### ISSUE THREAD

**Issue by lazywhite** [anlek/mongify#104]
```
/usr/local/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (Could not find 'mysql2' (~> 0.3.10) - did find: [mysql2-0.4.4] (LoadError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.3.0:/usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0', execute `gem env` for more information)
	from /usr/local/ruby-2.3.1/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/local/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/mysql2_adapter.rb:3:in `<top (required)>'
	from /usr/local/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `block in require'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/connection_specification.rb:50:in `resolve_hash_connection'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/connection_specification.rb:29:in `spec'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:40:in `setup_connection_adapter'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:56:in `has_connection?'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:95:in `check_sql_connection'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:64:in `execute'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/lib/mongify/cli/application.rb:28:in `execute!'
	from /usr/local/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/mongify-1.2.4/bin/mongify:15:in `<top (required)>'
	from /usr/local/ruby/bin/mongify:23:in `load'
	from /usr/local/ruby/bin/mongify:23:in `<main>'
```

but after run 'gem install activerecord-mysql2-adapter'  , it still prompt this error

**Comment by pedrosalpr** [comment]
Try change the line `adapter "mysql2"` to `adapter "mysql"`.
And install `gem install activerecord-mysql-adapter`
I run with mysql instead of mysql2

**Comment by jcavell** [comment]
Hi, I'm getting variations of:

```/Library/Ruby/Gems/2.0.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)``` 

Irrespective of what version of Ruby I'm using. I've tried using both mysql and mysql2 gems to no avail. I've obviously added the gems manually and via a Gemfile, but it still doesn't work.

I'm using Mac OSX with Rbenv.

```activemodel (4.2.8, 4.2.4)
activerecord (4.2.8, 4.2.4)
activerecord-mysql-adapter (0.0.1)
activesupport (4.2.8, 4.2.4)
arel (6.0.4)
bigdecimal (1.2.6)
bson (1.12.5)
bson_ext (1.12.5)
builder (3.2.3)
bundler (1.14.6)
highline (1.7.8)
i18n (0.8.1)
io-console (0.4.3)
json (1.8.6, 1.8.1)
minitest (5.10.1, 5.4.3)
mongify (1.3.1)
mongo (1.12.5)
mysql (2.9.1)
mysql2 (0.3.21)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
test-unit (3.0.8)
thread_safe (0.3.6)
tzinfo (1.2.3)
```

Thanks
