### ISSUE TITLE
undefined method `instance' for ActiveSupport::Deprecation:Class

### ISSUE THREAD

**Issue by dimasusername** [anlek/mongify#116]
/Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:124:in `initialize': undefined method `instance' for ActiveSupport::Deprecation:Class (NoMethodError)
Did you mean?  instance_of?
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/core_ext/load_error.rb:30:in `<top (required)>'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/core_ext.rb:3:in `require'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/core_ext.rb:3:in `block in <top (required)>'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/core_ext.rb:2:in `each'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/activesupport-5.0.0.1/lib/active_support/core_ext.rb:2:in `<top (required)>'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/mongify-0.3.1/lib/mongify.rb:4:in `require'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/mongify-0.3.1/lib/mongify.rb:4:in `<top (required)>'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/mongify-0.3.1/lib/mongify/cli.rb:1:in `require'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/mongify-0.3.1/lib/mongify/cli.rb:1:in `<top (required)>'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/mongify-0.3.1/bin/mongify:10:in `require'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/gems/mongify-0.3.1/bin/mongify:10:in `<top (required)>'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/bin/mongify:23:in `load'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/bin/mongify:23:in `<main>'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dmitriikharlamov/.rvm/gems/ruby-2.3.1@sql2mongo/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dimasusername** [comment]
bundler installed version 0.3.1 for some unknown reason
