### ISSUE TITLE
connecting to the database(no_sql_connection) is not working

### ISSUE THREAD

**Issue by shu74** [anlek/mongify#127]
When i tried to check the connection. I always get this error.

SQL connection works
/home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/database/no_sql_connection.rb:82:in `has_connection?': undefined method `connected?' for #<Mongo::DB:0x205fbc0> (NoMethodError)
Did you mean?  connection
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:104:in `check_nosql_connection'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:69:in `execute'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/application.rb:28:in `execute!'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/bin/mongify:15:in `<top (required)>'
	from /usr/bin/ruby/bin/mongify:22:in `load'
	from /usr/bin/ruby/bin/mongify:22:in `<main>'
	from /usr/bin/ruby/bin/ruby_executable_hooks:15:in `eval'
	from /usr/bin/ruby/bin/ruby_executable_hooks:15:in `<main>'

Can Someone please answer me quickly?

**Comment by kamrankhatti** [comment]
Whats your `database.config` file, could you share it?

**Comment by shu74** [comment]
sql_connection do
 adapter   "mysql2"
 host      "127.0.0.1"
 username  "root"
 password  "toor"
 database  "music"
end

mongodb_connection do
 host   "127.0.0.1"
 port  "27017"
 database "music"
end

**Comment by shu74** [comment]
The connection finally works, but when i try to process it, it shows me this error.

/home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/configuration.rb:14:in `instance_eval': undefined method `table' for #<Mongify::Configuration:0x1804cf8> (NoMethodError)
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/configuration.rb:14:in `instance_eval'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/configuration.rb:14:in `parse'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/options.rb:78:in `config_file'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/options.rb:58:in `parse'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/application.rb:27:in `execute!'
	from /home/hduser/.rvm/rubies/ruby-2.3.3/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/bin/mongify:15:in `<top (required)>'
	from /usr/bin/ruby/bin/mongify:22:in `load'
	from /usr/bin/ruby/bin/mongify:22:in `<main>'
	from /usr/bin/ruby/bin/ruby_executable_hooks:15:in `eval'
	from /usr/bin/ruby/bin/ruby_executable_hooks:15:in `<main>'

**Comment by shu74** [comment]
my ruby version.

ruby 2.3.3p222 (2016-11-21 revision 56859) [armv7l-linux-eabih

**Comment by shu74** [comment]
Thanks for your help. 

Everything is fine

**Comment by kamrankhatti** [comment]
Sounds good.

**Comment by Faizan227** [comment]
For SQL we also have to use the adpter of mysql?
