### ISSUE TITLE
Error updating references

### ISSUE THREAD

**Issue by obissick** [anlek/mongify#131]
`/home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/db.rb:559:in `rescue in command': Database command 'update' failed: Unknown option to update command: multi (Mongo::OperationFailure)                      | ETA:  --:--:--
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/db.rb:555:in `command'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/collection_writer.rb:314:in `block in send_write_command'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/functional/logging.rb:55:in `block in instrument'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/functional/logging.rb:20:in `instrument'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/functional/logging.rb:54:in `instrument'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/collection_writer.rb:313:in `send_write_command'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/collection.rb:1076:in `send_write'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongo-1.10.2/lib/mongo/collection.rb:497:in `update'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/database/no_sql_connection.rb:145:in `remove_pre_mongified_ids'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/translation/processor_common.rb:116:in `block in remove_pre_mongified_ids'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/translation/processor_common.rb:114:in `each'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/translation/processor_common.rb:114:in `remove_pre_mongified_ids'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/translation/process.rb:18:in `process'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/cli/command/worker.rb:68:in `execute'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/cli/application.rb:28:in `execute!'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/bin/mongify:15:in `<top (required)>'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/mongify:23:in `load'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/mongify:23:in `<main>'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'`

Not sure if this has to do with the mongo version.

**Comment by anlek** [comment]
What version of MongoDB are you running?

**Comment by obissick** [comment]
The latest version, 3.4.2.

**Comment by anlek** [comment]
Unfortunately, Mongify doesn't work on MongoDB 3.2 or higher :(
