### ISSUE TITLE
Sy command option work? Some documentantion how to used it? 

### ISSUE THREAD

**Issue by Jankko** [anlek/mongify#169]
root@MongiUbu:/var/lib/gems/2.2.0/gems/mongify-1.3.2# mongify sy database.config translation.rb
/var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql_adapter.rb:3           46:in `query': Mysql::Error: Unknown column 't.updated_at' in 'where clause': SELECT t.* FROM departm           ents t, __mongify_sync_helper__ u WHERE t.updated_at > u.last_updated_at AND u.table_name = 'departme           nts' (ActiveRecord::StatementInvalid)
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql           _adapter.rb:346:in `block in exec_without_stmt'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstr           act_adapter.rb:484:in `block in log'
        from /var/lib/gems/2.2.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumen           ter.rb:20:in `instrument'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstr           act_adapter.rb:478:in `log'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql           _adapter.rb:345:in `exec_without_stmt'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql           _adapter.rb:255:in `exec_query'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstr           act/database_statements.rb:356:in `select'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql           _adapter.rb:479:in `select'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstr           act/database_statements.rb:32:in `select_all'
        from /var/lib/gems/2.2.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstr           act/query_cache.rb:70:in `select_all'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/lib/mongify/database/sql_connection.rb:108:in `se           lect_by_query'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/lib/mongify/translation/sync.rb:61:in `block in s           ync_data'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/lib/mongify/translation/sync.rb:58:in `each'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/lib/mongify/translation/sync.rb:58:in `sync_data'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/lib/mongify/translation/sync.rb:29:in `sync'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/lib/mongify/cli/command/worker.rb:75:in `execute'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/lib/mongify/cli/application.rb:28:in `execute!'
        from /var/lib/gems/2.2.0/gems/mongify-1.3.2/bin/mongify:17:in `<top (required)>'
        from /usr/local/bin/mongify:23:in `load'
        from /usr/local/bin/mongify:23:in `<main>'

**Comment by anlek** [comment]
Looks like you might have some hidden characters in your setup. Your `departments` has a space between the `m` and the `e` (so the system sees it as `departm ents`).
Try retyping the name in the translation file.
