### ISSUE TITLE
is there any support for mongodb authentication?

### ISSUE THREAD

**Issue by am05mhz** [anlek/mongify#176]
is there any support for mongodb authentication? i did not found where to config this

and my migration is failed because of no permission when create table or index

> /var/lib/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:1165:in 'rescue in generate_indexes': Failed to create index {:name=>"pre_mongified_id_1", :key=>{"pre_mongified_id"=>1}} with the following error: Database command 'createIndexes' failed: not authorized on biblio to execute command { createIndexes: "books", indexes: [ { name: "pre_mongified_id_1", key: { pre_mongified_id: 1 } } ] } (Mongo::OperationFailure)
>         from /var/lib/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:1157:in 'generate_indexes'
>         from /var/lib/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:564:in 'create_index'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/database/no_sql_connection.rb:159:in 'create_pre_mongified_id_index'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/processor_common.rb:30:in 'block in setup_db_index'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/processor_common.rb:29:in 'each'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/processor_common.rb:29:in 'setup_db_index'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/process.rb:13:in 'process'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/cli/command/worker.rb:72:in 'execute'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/cli/application.rb:28:in 'execute!'
>         from /var/lib/gems/2.3.0/gems/mongify-1.3.2/bin/mongify:17:in '<top (required)>'
>         from /usr/local/bin/mongify:23:in 'load'
>         from /usr/local/bin/mongify:23:in '<main>'

**Comment by sbodrero** [comment]
Hi did you managed to fix this ?
Thanks forward.

**Comment by anlek** [comment]
No, sorry. I believe I'm going to archive this project as I'm prioritizing different things in life at the moment. I'd love to update this project at some point though

**Comment by sbodrero** [comment]
Thank you.
