### ISSUE TITLE
String not valid UTF-8

### ISSUE THREAD

**Issue by jwerre** [anlek/mongify#31]
```
    /Library/Ruby/Gems/2.0.0/gems/bson-1.8.6/lib/bson/bson_c.rb:6:in `serialize': String not valid UTF-8 (BSON::InvalidStringEncoding)
        from /Library/Ruby/Gems/2.0.0/gems/bson-1.8.6/lib/bson/bson_c.rb:6:in `serialize'
        from /Library/Ruby/Gems/2.0.0/gems/mongo-1.8.6/lib/mongo/collection.rb:1098:in `block in insert_documents'
        from /Library/Ruby/Gems/2.0.0/gems/mongo-1.8.6/lib/mongo/collection.rb:1097:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/mongo-1.8.6/lib/mongo/collection.rb:1097:in `insert_documents'
        from /Library/Ruby/Gems/2.0.0/gems/mongo-1.8.6/lib/mongo/collection.rb:375:in `insert'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/database/no_sql_connection.rb:98:in `insert_into'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/translation/process.rb:47:in `block (2 levels) in copy_data'
        from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.2/lib/active_record/result.rb:21:in `block in each'
        from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.2/lib/active_record/result.rb:21:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/activerecord-4.0.2/lib/active_record/result.rb:21:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/translation/process.rb:46:in `block in copy_data'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/translation/process.rb:43:in `each'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/translation/process.rb:43:in `copy_data'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/translation/process.rb:22:in `process'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/cli/command/worker.rb:67:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/lib/mongify/cli/application.rb:28:in `execute!'
        from /Library/Ruby/Gems/2.0.0/gems/mongify-1.0.0/bin/mongify:15:in `<top (required)>'
        from /usr/bin/mongify:23:in `load'
        from /usr/bin/mongify:23:in `<main>'
```

**Comment by tjdavis1111** [comment]
I attempted the 'encoding "utf8"' solution prior to submitting #86, it did not solve the problem.  That is why I created #86.

**Comment by Moutaouakil** [comment]
Thank you @brandom : `encoding "utf8"` saved my day

**Comment by andyfry01** [comment]
Adding `encoding "utf8"` to both `sql_connection do` and `mongodb_connection do` fixed it for me too! Thanks @brandom
